global:
  scrape_interval: 15s

scrape_configs:
  # Prometheus self-metrics (keep this)
  - job_name: "prometheus"
    static_configs:
      - targets:
          - "localhost:9090"

  # Django app metrics
  - job_name: "django"
    metrics_path: /metrics/
    static_configs:
      - targets:
          - "django:8000"
